title: MOO4Modelica
description: Multi-objective Optimization framework/pipeline for Modelica
theme: just-the-docs

url: https://wangzizhe.github.io/MOO4Modelica

aux_links:
  Template Repository: https://wangzizhe.github.io/MOO4Modelica